### ISSUE TITLE
Add codegen support for PHP Namespaces client library

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#47]
Add code generation support the PHP with namespaces client. 
See https://github.com/kaltura/KalturaGeneratedAPIClientsPHP53/tree/master/tests for code examples.

@jessp01 - please share any important implementation notes and other useful references.

**Comment by jessp01** [comment]
Please see https://github.com/kaltura/KalturaGeneratedAPIClientsPHP53/blob/master/tests/Test/Zend2ClientTester.php

A LucyBot codegen for this client can be written based on this example.

**Comment by bobby-brennan** [comment]
@jessp01 - how do I import the library? Here's the generated code so far:

```php
<?php
  /**
   * @namespace
   */
  namespace KalturaCode;
  use Kaltura\Client\Configuration as KalturaConfiguration;
  use Kaltura\Client\Client as KalturaClient;
  use Kaltura\Client\Enum\SessionType as KalturaSessionType;
  use Kaltura\Client\ApiException;
  use Exception;

  $config = new KalturaConfiguration();
  $config->serviceUrl = 'https://www.kaltura.com';
  $client = new KalturaClient($config);
  $ks = $client->generateSession(
      "YOUR_KALTURA_SECRET",
      "YOUR_USER_ID",
      KalturaSessionType::ADMIN,
      "YOUR_PARTNER_ID");
  $client->setKS($ks);
  $filter = new KalturaMediaEntryFilter();
  $pager = new KalturaFilterPager();

  try {
    $result = $client->getMediaService()->listAction($filter, $pager);
    var_dump($result);
  } catch (Exception $e) {
    echo $e->getMessage();
  }
?>
```

But when trying to run it, I get:
```bash
PHP Fatal error:  Uncaught Error: Class 'Kaltura\Client\Configuration' not found in /home/ubuntu/downloads/php/test.php:12
```

**Comment by jessp01** [comment]
Hi @bobby-brennan,

See https://github.com/kaltura/KalturaGeneratedAPIClientsPHP53/blob/master/tests/run.php#L13
Also:
```
<?php
$config->serviceUrl = 'https://www.kaltura.com';
```
Should be:
```
<?php
$config->setServiceUrl('https://www.kaltura.com');
```
because ```Kaltura\Client\Configuration::$serviceUrl``` is declared as a private member of the class.

**Comment by bobby-brennan** [comment]
OK thanks, a bit closer now. I'm guessing the client will know how to get ClassLoader.php?

Now when I run the following, I get 
```bash
Uncaught Error: Class 'SimpleXMLElement' not found in /home/ubuntu/downloads/php/php53/library/Kaltura/Client/Service/MediaService.php:505
```

```php
<?php
  use Kaltura\Client\Configuration as KalturaConfiguration;
  use Kaltura\Client\Client as KalturaClient;
  use Kaltura\Client\Enum\SessionType;
  use Kaltura\Client\Type\MediaEntryFilter;
  use Kaltura\Client\Type\FilterPager;
  use Kaltura\Client\ApiException;
  use Exception;

  // load zend framework 2
  require_once(dirname(__FILE__).'/ClassLoader/ClassLoader.php');
  $loader = new Symfony\Component\ClassLoader\ClassLoader();
  $loader->addPrefix('Kaltura', dirname(__FILE__).'/php53/library');
  $loader->register();

  $config = new KalturaConfiguration();
  $config->setServiceUrl('https://www.kaltura.com');
  $client = new KalturaClient($config);
  $ks = $client->generateSession(
      "YOUR_KALTURA_SECRET",
      "YOUR_USER_ID",
      SessionType::ADMIN,
      "YOUR_PARTNER_ID");
  $client->setKS($ks);
  $filter = new MediaEntryFilter();
  $pager = new FilterPager();

  try {
    $result = $client->getMediaService()->listAction($filter, $pager);
    var_dump($result);
  } catch (Exception $e) {
    echo $e->getMessage();
  }
?>
```

**Comment by jessp01** [comment]
Hi @bobby-brennan,

```SimpleXMLElement``` is provided by PHP's SimpleXML extension:
https://github.com/php/php-src/blob/6053987bc27e8dede37f437193a5cad448f99bce/ext/simplexml/simplexml.c#L1922
http://php.net/manual/en/class.simplexmlelement.php

What's the output for:
```
# php -m|grep -i xml
```
in your ENV?

**Comment by jessp01** [comment]
Also, why do you have:
```php
use Exception;
```
?

That would just yield a warning:
```
PHP Warning:  The use statement with non-compound name 'Exception' has no effect
```

**Comment by bobby-brennan** [comment]
OK got rid of `use Exception`.

`php -m|grep -i xml` gives me just `libxml`

**Comment by bobby-brennan** [comment]
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

**Comment by jessp01** [comment]
```
# apt install php-xml
```
Should fix it for you.

**Comment by bobby-brennan** [comment]
That works! Thanks.

**Comment by jessp01** [comment]
@zoharbabin - how do you want to label this client? obviously and for reasons I stated before 'php53' is not a good name. I suggest "PHP with name-space support". It's a little long but as short as can be while remaining descriptive, IMHO.

**Comment by jessp01** [comment]
@bobby-brennan - mostly, the codegen is fine but there's an issue with services that are implemented as plugins [for example, the metadata.* services].

The behaviour here should be similar to that of the `php5` client. To wit:
https://github.com/kaltura/developer-platform/commit/782d4edd56011743265ff47f3290bd72d3993610

For the php53 client, it should look like this:
```php
<?php
$<%-p %>Plugin = <%- p.charAt(0).toUpperCase() + p.substring(1) %>ClientPlugin::get($client);
$result = $<%- plugins.length ? plugins[0] + 'Plugin' : 'client' %>-><%- service %>-><%- action %>(<%- parameterNames.join(', ') %>);
```

So, for example, the code here https://developer.kaltura.com:8443/workflows/Enrich_and_Organize_Metadata/Working_with_metadata;step=1, should be changed so that:
```php
<?php
$result = $client->getMetadataProfileService()->add($metadataProfile, $xsdData, $viewsData);
```
Becomes:
```php
<?php
$metadataPlugin = MetadataPlugin::get($client);
$result = $metadataPlugin->metadataProfile->add($metadataProfile, $xsdData, $viewsData);
```

Also, the bootstrapping section should change so that:
```php
<?php
  use Kaltura\Client\Enum\MetadataObjectType;
  use Kaltura\Client\Enum\MetadataProfileCreateMode;
  use Kaltura\Client\Type\MetadataProfile;
```
Becomes:
```php
<?php
  use Kaltura\Client\Plugin\Metadata\MetadataPlugin;
  use Kaltura\Client\Plugin\Metadata\Enum\MetadataObjectType;
  use Kaltura\Client\Plugin\Metadata\Enum\MetadataProfileCreateMode;
  use Kaltura\Client\Plugin\Metadata\Type\MetadataProfile;
```
Please notice that in addition to the path changes, `use Kaltura\Client\Plugin\Metadata\MetadataPlugin;` is also required. Of course, the metadata service is just an example, the same is true to other services that are implemented as plugins.

Thanks,

**Comment by zoharbabin** [comment]
@jessp01  - let's name it `PHP (Namespaces)`

**Comment by jessp01** [comment]
@zoharbabin - done. @bobby-brennan - please fix the plugins issue as per the above.

**Comment by bobby-brennan** [comment]
Fixed in 0b9f1df6cef1625c040ae3e694b5697859cbf1f2

**Comment by jessp01** [comment]
It's only partially fixed I'm afraid...
Still see:
```php
<?php
  use Kaltura\Client\Enum\MetadataObjectType;
  use Kaltura\Client\Enum\MetadataProfileCreateMode;
  use Kaltura\Client\Type\MetadataProfile;
```
whereas, it should be:
```php
    use Kaltura\Client\Plugin\Metadata\MetadataPlugin;
    use Kaltura\Client\Plugin\Metadata\Enum\MetadataObjectType;
    use Kaltura\Client\Plugin\Metadata\Enum\MetadataProfileCreateMode;
    use Kaltura\Client\Plugin\Metadata\Type\MetadataProfile;
```

Also
```php
$metadataPlugin = MetadataPlugin::get($client);
```
Is initialised immediately after the `use` statements. At a bare minimum, it needs to be initialised after 
```php
$client = new KalturaClient($config);
```
since it passes $client as a param and it would be best if it could come right before:
```php
    $result = $metadataPlugin->metadataProfile->add($metadataProfile, $xsdData, $viewsData);
```

**Comment by jessp01** [comment]
```php
  use Kaltura\Client\Plugin\MetadataPlugin;
```
Should be:
```php
use Kaltura\Client\Plugin\Metadata\MetadataPlugin;
```

I fixed that for you here: 1d3d2abdbbf5c3355537406b082437764b11d32d
